name: Build and Release

on:
  push:
    branches: [ master ]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          cd ./MediaPlayerRPC/
          dotnet build -c Release

#      - name: Create zip
#        run: |
#          7z -tZip a exec\SecureFolder.zip build\windows\runner\Release\

      - name: Create release
        uses: softprops/action-gh-release@v1
        #         if: startsWith(github.ref, 'refs/tags/')
        with:
          name: MediaPlayerRPC
          tag_name: v0.0.1
          prerelease: true
          generate_release_notes: true
          files: ./MediaPlayerRPC/bin/Release/*
          body_path: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_REPOSITORY: dhzdhd/W11-MediaPlayerRPC